spring.application.name=eureka-server
server.port=8761

# Eureka Server Configuration
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Server security settings
eureka.client.eureka-server-read-timeout-seconds=5
eureka.client.eureka-server-connect-timeout-seconds=5
eureka.server.enable-self-preservation=true
eureka.server.renewal-percent-threshold=0.85

# Logging
logging.level.root=WARN
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=WARN
